spring:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://bangi98.cafe24.com:3306/pins?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  sql:
    init:
      mode: always
server:
  port: 9090