spring:
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false
  profiles:
    active: local # local, dev, prod
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
      enabled: true
      resolve-lazily: true
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

---
spring:
  profiles:
    active: local

---
spring:
  profiles:
    active: dev
---

---
spring:
  profiles:
    active: prod
---