spring:
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true
  profiles:
    active: local # local, dev, prod
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
      enabled: true
      resolve-lazily: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  jackson:
    serialization:
      fail-on-empty-beans: false
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration