spring:
  jpa:
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: rds.dev.host
    username: hada
    password: rds.dev.password
  sql:
    init:
      mode: always
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 8081
jwt:
  secret: jwt.secret
cloud:
  aws:
    env: dev
    credentials:
      accessKey: aws.dev.s3.accessKey
      secretKey: aws.dev.s3.secretKey
    s3:
      bucket: hada-pins
    region:
      auto: false
      static: ap-northeast-2
    stack:
      auto: false
    cloudFront:
      distributionDomain: https://d21ye6uqd6ovq2.cloudfront.net
  minio:
    access-key: minioadmin
    secret-key: minioadmin
    endpoint: http://127.0.0.1:9000
  redis:
    host: redis.host
    port: redis.port

logging:
  slack:
    webhook-uri: hooks.slack.com
  config: classpath:logback-spring.xml

kakao:
  key: dev.kakao.key

cafe24:
  key: dev.cafe24.key

google:
  key: dev.google.key
