-- insert into user (`id`, `name`, `nick_name`, `res_red_number`, `age`,`gender`,`image`) values (1, 'bang', 'bbangi', 9801031, 24,'Male','http://...');
--
-- insert into user (`id`, `name`, `nick_name`, `res_red_number`, `age`,`gender`,`image`) values (2, 'park', 'ppark', 9302011, 28,'Male','http://...');
--
-- insert into user (`id`, `name`, `nick_name`, `res_red_number`, `age`,`gender`,`image`) values (3, 'kim', 'kiki', 9202011, 29,'Female','http://...');
--
